# Generated by Django 5.2.11 on 2026-02-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_membershiprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiprequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
