# Generated by Django 5.2.11 on 2026-02-18 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_membershiprequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclub',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
